### ISSUE TITLE
Adding tokens not working in 'Create a Pool' when returning to a partially created pool

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1651]
**Describe the bug**
When tapping the 'Add tokens' button, empty rows are being created. This was happening for a 'saved pool' that was started a while back but not completed.

**To Reproduce**
1. Go to 'Create a pool'
2. Start creating a pool. 
3. Leave the Create a Pool interface
4. Go back to Create a Pool 
5. Try adding new tokens

Loom:

https://www.loom.com/share/887e448e2fa54daaaca77049a59da97a

Browser console errors:

```
instrument.js:109 TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (runtime-dom.esm-bundler.js:10:16)
    at T (runtime-core.esm-bundler.js:4148:9)
    at _ (runtime-core.esm-bundler.js:4068:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at U (runtime-core.esm-bundler.js:4797:21)
    at L (runtime-core.esm-bundler.js:4680:17)
    at C (runtime-core.esm-bundler.js:4385:17)
    at y (runtime-core.esm-bundler.js:3984:17)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at O (runtime-core.esm-bundler.js:4220:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at O (runtime-core.esm-bundler.js:4220:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at O (runtime-core.esm-bundler.js:4220:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at C (runtime-core.esm-bundler.js:4385:17)
    at y (runtime-core.esm-bundler.js:3984:17)
    at k (runtime-core.esm-bundler.js:4305:13)
    at O (runtime-core.esm-bundler.js:4213:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at E.c [as fn] (runtime-core.esm-bundler.js:4606:17)
    at E.run (reactivity.esm-bundler.js:160:29)
    at N (runtime-core.esm-bundler.js:4467:26)
    at j (runtime-core.esm-bundler.js:4400:13)
    at y (runtime-core.esm-bundler.js:3991:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at C (runtime-core.esm-bundler.js:4385:17)
    at y (runtime-core.esm-bundler.js:3984:17)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at O (runtime-core.esm-bundler.js:4220:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at E.c [as fn] (runtime-core.esm-bundler.js:4606:17)
    at E.run (reactivity.esm-bundler.js:160:29)
    at Qa (runtime-core.esm-bundler.js:6990:36)
    at Oi (runtime-core.esm-bundler.js:7221:17)
    at async G (ChooseWeights.vue:236:13)
(anonymous) @ instrument.js:109
ni @ runtime-core.esm-bundler.js:7061
ti @ runtime-core.esm-bundler.js:7039
Qa @ runtime-core.esm-bundler.js:6993
Oi @ runtime-core.esm-bundler.js:7221
Promise.then (async)
vi @ runtime-core.esm-bundler.js:7120
wi @ runtime-core.esm-bundler.js:7142
_i @ runtime-core.esm-bundler.js:7145
y @ runtime-core.esm-bundler.js:7410
B @ reactivity.esm-bundler.js:358
D @ reactivity.esm-bundler.js:331
(anonymous) @ reactivity.esm-bundler.js:475
S @ usePoolCreation.ts:259
H @ ChooseWeights.vue:254
Qa @ runtime-core.esm-bundler.js:6990
ei @ runtime-core.esm-bundler.js:6999
n @ runtime-dom.esm-bundler.js:347
r @ helpers.js:73
instrument.js:109 TypeError: Cannot read properties of null (reading 'emitsOptions')
    at Et (runtime-core.esm-bundler.js:958:29)
    at N (runtime-core.esm-bundler.js:4446:13)
    at j (runtime-core.esm-bundler.js:4400:13)
    at y (runtime-core.esm-bundler.js:3991:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at O (runtime-core.esm-bundler.js:4220:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at O (runtime-core.esm-bundler.js:4220:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at O (runtime-core.esm-bundler.js:4220:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at C (runtime-core.esm-bundler.js:4385:17)
    at y (runtime-core.esm-bundler.js:3984:17)
    at k (runtime-core.esm-bundler.js:4305:13)
    at O (runtime-core.esm-bundler.js:4213:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at E.c [as fn] (runtime-core.esm-bundler.js:4606:17)
    at E.run (reactivity.esm-bundler.js:160:29)
    at N (runtime-core.esm-bundler.js:4467:26)
    at j (runtime-core.esm-bundler.js:4400:13)
    at y (runtime-core.esm-bundler.js:3991:21)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at C (runtime-core.esm-bundler.js:4385:17)
    at y (runtime-core.esm-bundler.js:3984:17)
    at U (runtime-core.esm-bundler.js:4761:17)
    at L (runtime-core.esm-bundler.js:4704:21)
    at O (runtime-core.esm-bundler.js:4220:13)
    at _ (runtime-core.esm-bundler.js:4071:13)
    at y (runtime-core.esm-bundler.js:3988:21)
    at E.c [as fn] (runtime-core.esm-bundler.js:4606:17)
    at E.run (reactivity.esm-bundler.js:160:29)
    at Qa (runtime-core.esm-bundler.js:6990:36)
    at Oi (runtime-core.esm-bundler.js:7221:17)
(anonymous) @ instrument.js:109
ni @ runtime-core.esm-bundler.js:7061
ti @ runtime-core.esm-bundler.js:7039
Qa @ runtime-core.esm-bundler.js:6993
Oi @ runtime-core.esm-bundler.js:7221
Promise.then (async)
vi @ runtime-core.esm-bundler.js:7120
wi @ runtime-core.esm-bundler.js:7142
_i @ runtime-core.esm-bundler.js:7145
y @ runtime-core.esm-bundler.js:7410
B @ reactivity.esm-bundler.js:358
D @ reactivity.esm-bundler.js:331
(anonymous) @ reactivity.esm-bundler.js:475
(anonymous) @ ChooseWeights.vue:293
Y @ ChooseWeights.vue:292
H @ ChooseWeights.vue:256
await in H (async)
Qa @ runtime-core.esm-bundler.js:6990
ei @ runtime-core.esm-bundler.js:6999
n @ runtime-dom.esm-bundler.js:347
r @ helpers.js:73

```

**Comment by eduardopelitti** [comment]
Hi! Just to add to this report, because I've been having this issue for a few days now and finally nailed down a consistent reproduction, I can confirm that this happens as well when returning to the first step after initially adding tokens.

https://user-images.githubusercontent.com/3876078/174514194-f99c5cc8-fb37-41fe-9e56-0b8e4a90e841.mov

1- Go to Pool Creation, add two tokens.
2- Move to the next step.
3- Return to the first step by pressing on Back on the steps breadcrumb
4- Add a new token, notice the empty row.

**Comment by nayane95** [comment]
This bug couldn't recreate in the local dev environment (still remain in the live release). In the local dev environment, there is a vue warn which provides during adding tokens. This might be the issue (refer to the image).

![Screenshot 2022-08-20 at 13 22 19](https://user-images.githubusercontent.com/38324084/185735176-c4a94b3b-5e69-403b-a55a-3370738e47c5.png)

@garethfuller

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
